### ISSUE TITLE
Bug in combat

### ISSUE THREAD

**Issue by KochiTusker** [KochiTusker/dungeon-crawler#8]
It seems that most of the times the combat works fine but there are occasions that it falls into an infinite loop. The levelling up system does not quite work either. I think this will require further testing

**Comment by KochiTusker** [comment]
This is in regards to Game_Main_Windowv1_0_7 and Storylinev1_0_5

**Comment by Odissus** [comment]
### Quick Links
[main window](https://github.com/KochiTusker/dungeon-crawler/blob/main/Modular%20GUI/Game_Main_Windowv1_0_7.py)
[storyline](https://github.com/KochiTusker/dungeon-crawler/blob/main/Modular%20GUI/Storylinev1_0_5.py)
### Description
Random infinite loop in [storyline](https://github.com/KochiTusker/dungeon-crawler/blob/main/Modular%20GUI/Storylinev1_0_5.py), `combat_scenarios` function.

It would be useful if you could test it to add anything to the issue @KochiTusker

**Comment by KochiTusker** [comment]
Used the Pycharm Debugger and found the issue lies with the villain damage rolls. The line with:

`damage = self.current_villain.attack() ` starts an infinite loop when the damage rolls are low

` def combat_scenarios(self, command):
        Output_Text = ""
        Success = False
        while self.current_villain.health >= 1:
            print("We're in the loop")
            damage = self.current_villain.attack()
            Output_Text = f"""{self.current_villain.name} hits you for {damage}"""
            cur_health = self.player.get_health()
            self.player.set_health(cur_health - damage)
            if self.player.get_health() < 1:
                self._set_checkpoint("0")
                self._set_handler(self.__hospital)
            else:
                diceroll = self.player.attack()
                self.current_villain.health -= diceroll
                Output_Text += f"""\nYou strike back using your {self.player.get_weapon()} and do {diceroll} damage
{self.current_villain.name} has {self.current_villain.health} left"""
        self._set_checkpoint(self.new_combat_checkpoint)
        self._set_handler(self.new_combat_handler)
        Success = True
        return Success, Output_Text`

I tried changing this up by adding a get and set health method in the Villain class and removing the attack method. This looks like this

`class Villain:  # villain class that is used for all the enemies in game
    def __init__(self, name, race, health, weapon, power):
        self.name = name
        self.race = race
        self._health = health
        self.weapon = weapon
        self.power = power
    def get_health(self):
        return self._health
    def set_health(self, value: int):
        self._health = value

    def combat_scenarios(self, command):
        Output_Text = ""
        Success = False
        while self.current_villain.get_health() >= 1:
            print("We're in the loop")
            damage = random.randint(1, self.current_villain.power)
            Output_Text = f"""{self.current_villain.name} hits you for {damage}"""
            cur_health = self.player.get_health()
            self.player.set_health(cur_health - damage)
            if self.player.get_health() < 1:
                self._set_checkpoint("0")
                self._set_handler(self.__hospital)
            else:
                diceroll = self.player.attack()
                villainhealth = self.current_villain.get_health()
                self.current_villain.set_health(villainhealth - diceroll)
                Output_Text += f"""\nYou strike back using your {self.player.get_weapon()} and do {diceroll} damage
{self.current_villain.name} has {self.current_villain.get_health()} left"""
        self._set_checkpoint(self.new_combat_checkpoint)
        self._set_handler(self.new_combat_handler)
        Success = True
        return Success, Output_Text
`

**Comment by KochiTusker** [comment]
However, the new solution does not fix the bug

**Comment by KochiTusker** [comment]
Solution found to endless loop was to get rid of "else" statement in `def combat_scenarios`. However, there remains an issue that when the player health drops below 1, the handler does not set the "map" to __hospital as it should do. 

    def combat_scenarios(self, command):
        Output_Text = ""
        Success = False
        while self.current_villain.health >= 1:
            print("We're in the loop")
            damage = self.current_villain.attack()
            cur_health = self.player.get_health()
            self.player.set_health(cur_health - damage)
            Output_Text += f"""\n{self.current_villain.name} hits you for {damage} damage
            You have {self.player.get_health()} health left"""
            if self.player.get_health() < 1:
                self._set_checkpoint("0")
                self._set_handler(self.__hospital)
                Success = True
            diceroll = self.player.attack()
            self.current_villain.health -= diceroll
            Output_Text += f"""\nYou strike back using your {self.player.get_weapon()} and do {diceroll} damage
            {self.current_villain.name} has {self.current_villain.health} left"""
        self._set_checkpoint(self.new_combat_checkpoint)
        self._set_handler(self.new_combat_handler)
        Success = True
        return Success, Output_Text

**Comment by KochiTusker** [comment]
Issue turned out to be a fault in the `__hospital` method and has since been fixed
